"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import logging
from urllib import parse as urlparse

# Optional production helpers (install in production):
try:
    import dj_database_url
except Exception:
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv_file(dotenv_path):
    if not dotenv_path.exists():
        return

    for raw_line in dotenv_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_dotenv_file(BASE_DIR / '.env')

_logger = logging.getLogger('talentsift.storage')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# Read debug from environment; default to False in production
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Hosts allowed to serve the application (comma-separated in env)
_env_allowed_hosts = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
_default_allowed_hosts = ['localhost', '127.0.0.1', '[::1]', '.onrender.com']
ALLOWED_HOSTS = list(dict.fromkeys(_env_allowed_hosts + _default_allowed_hosts)) if _env_allowed_hosts else _default_allowed_hosts


# Cloudinary settings are optional at startup. If credentials are missing or malformed,
# we fall back to local file storage so the app can boot and surface the env issue cleanly.
_cloudinary_storage_config = None

_cloudinary_url = os.getenv('CLOUDINARY_URL', '').strip()
_cloudinary_cloud_name = os.getenv('CLOUDINARY_CLOUD_NAME', '').strip()
_cloudinary_api_key = os.getenv('CLOUDINARY_API_KEY', '').strip()
_cloudinary_api_secret = os.getenv('CLOUDINARY_API_SECRET', '').strip()

if _cloudinary_cloud_name and _cloudinary_api_key and _cloudinary_api_secret:
    _cloudinary_storage_config = {
        'CLOUD_NAME': _cloudinary_cloud_name,
        'API_KEY': _cloudinary_api_key,
        'API_SECRET': _cloudinary_api_secret,
    }
    _cloudinary_url = f'cloudinary://{_cloudinary_api_key}:{_cloudinary_api_secret}@{_cloudinary_cloud_name}'
    os.environ['CLOUDINARY_URL'] = _cloudinary_url

elif _cloudinary_url and _cloudinary_url.startswith('cloudinary://'):
    try:
        parsed = urlparse.urlparse(_cloudinary_url)
        if parsed.username and parsed.password and parsed.hostname:
            _cloudinary_storage_config = {
                'CLOUD_NAME': parsed.hostname,
                'API_KEY': parsed.username,
                'API_SECRET': parsed.password,
            }
    except Exception as e:
        _logger.exception('Failed to parse CLOUDINARY_URL: %s', e)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'signup',
    'signin',
    'corsheaders',
    'profil',
    'getUserData',
    'signout',
    'JobList',
    'createjob',
    'Up_del_ret_job',
    'AI_job_title',
    'Check_Ai_subs',
    'report',
    'checkout',
    'applications',
    'practice',
]

if _cloudinary_storage_config:
    INSTALLED_APPS += [
        'cloudinary_storage',
        'cloudinary',
    ]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise will be inserted here in production when available
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# Prefer a pooler URL in production (Render/Supabase). Falls back to DATABASE_URL, then sqlite for local dev.
DATABASE_URL = os.environ.get('DATABASE_URL_POOLER') or os.environ.get('DATABASE_URL')
if DATABASE_URL and dj_database_url:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` will gather files for the production server
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use WhiteNoise compressed manifest storage in production
STATICFILES_STORAGE = os.environ.get('STATICFILES_STORAGE', 'whitenoise.storage.CompressedManifestStaticFilesStorage')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

if _cloudinary_storage_config:
    CLOUDINARY_STORAGE = _cloudinary_storage_config
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Keep the legacy setting for older integrations; Django 5 uses STORAGES above.
DEFAULT_FILE_STORAGE = os.environ.get(
    'DEFAULT_FILE_STORAGE',
    'cloudinary_storage.storage.MediaCloudinaryStorage' if _cloudinary_storage_config else 'django.core.files.storage.FileSystemStorage'
)

# Emit a concise startup log so Render logs show which storage backend is active.
try:
    _display_cloudinary = os.environ.get('CLOUDINARY_URL', '')
    if _display_cloudinary:
        # mask credentials in display
        try:
            p = urlparse.urlparse(_display_cloudinary)
            if p.scheme == 'cloudinary':
                # cloudinary://key:secret@cloud_name
                display = f'cloudinary://****:****@{p.hostname}'
            else:
                display = _display_cloudinary
        except Exception:
            display = _display_cloudinary
    else:
        display = ''
    print(f'ACTIVE_STORAGE={DEFAULT_FILE_STORAGE} CLOUDINARY_URL={display}')
except Exception:
    pass


def _env_truthy(name, default='False'):
    return os.getenv(name, default).strip().lower() in {'1', 'true', 'yes', 'on'}


EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
# Keep the password exactly as provided by the environment, only trim accidental leading/trailing spaces.
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
if EMAIL_HOST_PASSWORD is not None:
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD.strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER).strip()
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '').strip()
BREVO_FROM_EMAIL = os.getenv('BREVO_FROM_EMAIL', DEFAULT_FROM_EMAIL).strip()
BREVO_FROM_NAME = os.getenv('BREVO_FROM_NAME', 'TalentSift').strip()
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY', '').strip()
SENDGRID_FROM_EMAIL = os.getenv('SENDGRID_FROM_EMAIL', DEFAULT_FROM_EMAIL).strip()
SENDGRID_FROM_NAME = os.getenv('SENDGRID_FROM_NAME', 'TalentSift').strip()

if DEBUG and (not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD):
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_USE_SSL = _env_truthy('EMAIL_USE_SSL', 'False')
EMAIL_USE_TLS = _env_truthy('EMAIL_USE_TLS', 'True' if not EMAIL_USE_SSL else 'False')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587' if EMAIL_USE_TLS or not EMAIL_USE_SSL else '465'))
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Increase to 1 hour or as needed
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token valid for 7 days
}

AUTH_USER_MODEL = "signup.User"

CORS_ALLOW_CREDENTIALS = True  # Enable credentials

# Read CORS and CSRF trusted origins from environment (comma-separated)
_env_cors_origins = [o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
_default_cors_origins = [
    'http://localhost:3000',
    'https://localhost:3000',
    os.getenv('FRONTEND_BASE_URL', '').rstrip('/'),
]
_production_cors_hosts = [
    'https://talentsift.live',
    'https://www.talentsift.live',
]
# If VERCEL_URL is provided (e.g. talentsift-liard.vercel.app), include it as an allowed origin.
_vercel_origin = None
if os.getenv('VERCEL_URL'):
    _vercel_origin = f"https://{os.getenv('VERCEL_URL').rstrip('/') }"

_frontend_base = os.getenv('FRONTEND_BASE_URL', '').rstrip('/')

_additional_origins = [o for o in (_frontend_base, _vercel_origin) if o]

CORS_ALLOWED_ORIGINS = [
    origin for origin in dict.fromkeys(
        _env_cors_origins + _default_cors_origins + _additional_origins + _production_cors_hosts
    ) if origin
]

# Remove CORS_ALLOW_ALL_ORIGINS to avoid conflicts with CORS_ALLOW_CREDENTIALS
CORS_ALLOW_ALL_ORIGINS = False  # Remove or set to False if present

_env_csrf_origins = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
_default_csrf_origins = [
    'http://localhost:3000',
    'https://localhost:3000',
    os.getenv('FRONTEND_BASE_URL', '').rstrip('/'),
    'https://*.vercel.app',
    'https://*.onrender.com',
]
_production_csrf_hosts = [
    'https://talentsift.live',
    'https://www.talentsift.live',
]

_additional_csrf = [o for o in (_frontend_base, _vercel_origin) if o]

CSRF_TRUSTED_ORIGINS = [
    origin for origin in dict.fromkeys(
        _env_csrf_origins + _default_csrf_origins + _additional_csrf + _production_csrf_hosts
    ) if origin
]

# Security settings for production
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'



STRIPE_TEST_PUBLIC_KEY = os.getenv('STRIPE_TEST_PUBLIC_KEY', '')
STRIPE_TEST_SECRET_KEY = os.getenv('STRIPE_TEST_SECRET_KEY', '')

# Frontend base URL used in email links and candidate redirects.
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'http://localhost:3000').rstrip('/')

# reCAPTCHA secret for server-side verification (leave empty in local dev)
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '')

# AI screening threshold: 8.0/10 = 80%
INTERVIEW_PASS_SCORE = float(os.getenv('INTERVIEW_PASS_SCORE', '8.0'))

# AI screening timing: 2 minutes per question + 5 minute buffer
INTERVIEW_MINUTES_PER_QUESTION = float(os.getenv('INTERVIEW_MINUTES_PER_QUESTION', '2.0'))
INTERVIEW_BUFFER_MINUTES = int(os.getenv('INTERVIEW_BUFFER_MINUTES', '5'))

