# Generated by Django 5.2.13 on 2026-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceattempt',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='user_answer_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
