# Generated by Django 5.2.13 on 2026-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practiceattempt_similarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='rubric_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
