# Generated by Django 5.2.13 on 2026-05-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_practicequestion_rubric_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSessionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0)),
                ('attempted_questions', models.IntegerField(default=0)),
                ('mcq_questions', models.IntegerField(default=0)),
                ('text_questions', models.IntegerField(default=0)),
                ('correct_mcq', models.IntegerField(default=0)),
                ('average_ai_score', models.FloatField(blank=True, null=True)),
                ('average_similarity', models.FloatField(blank=True, null=True)),
                ('completion_time_seconds', models.IntegerField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('improvement_areas', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='practice.practicesession')),
            ],
        ),
    ]
