# Generated by Django 5.2.13 on 2026-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_jobapplication_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='screening_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
