# Generated by Django 5.2.13 on 2026-07-12 11:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_jobapplication_screening_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='D:\\Projects\\TalentSift\\backend\\media'), upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='D:\\Projects\\TalentSift\\backend\\media'), upload_to='applications/resumes/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='profile_pictures/'),
        ),
    ]
